### ISSUE TITLE
KLIPSE error causes page to hang

### ISSUE THREAD

**Issue by isaacanderson** [jrheard/jrheard.github.io#15]
I'm not sure if it's a problem with KLIPSE or your blog but in your procedural-dungeon-generation-cellular-automata post if you change the first parameter in the first snippet to 0 the page hangs (chrome, win64).

**Comment by jrheard** [comment]
hey, sorry i didn't see this - good find, i need to upgrade my version of KLIPSE to one that prevents this from hanging (the latest version's able to do this). thanks for the report!
